### ISSUE TITLE
CSS not correctly applied to screenshots

### ISSUE THREAD

**Issue by leicht-io** [fwouts/react-screenshot-test#40] opened 2019-12-18 06:38 UTC
Hi again and thanks for continuing to help me out :)

After getting normalize.css to work i am running into another issue. The tests are running as expected but the generated screenshots for my components looks like the following:
![image](https://user-images.githubusercontent.com/3056379/71061794-2983af00-2169-11ea-99b2-936832dde307.png)

When it in fact should look like below:
![image](https://user-images.githubusercontent.com/3056379/71061789-24266480-2169-11ea-93a6-8f1db2fb7c78.png)

My test looks like the following:
```typescript
import React from 'react';
import { ReactScreenshotTest } from 'react-screenshot-test';
import { UIRoot } from '../../UIRoot';
import { UIButtonIcon } from './UIButtonIcon';

const icon = (
  <UIRoot>
    <UIButtonIcon icon="trash" />
  </UIRoot>
);

ReactScreenshotTest.create('UIButtonIcon')
  .viewport('Desktop', {
    width: 1024,
    height: 768
  })
  .viewport('iPhone X', {
    width: 375,
    height: 812,
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    isLandscape: false
  })
  .shoot('with label', icon)
  .run();
```
Am i missing something or is there a way to see the generated HTML or applied CSS?
Thanks :)

**Comment by fwouts** [comment] 2019-12-18 06:54
I'm not sure, sorry! Do you have a minimal code sample to reproduce the issue? Is this exclusively using SCSS? 

Being able to debug the generated HTML (which is served by ReactComponentServer) would indeed be quite helpful. How would you envision that working?

**Comment by fwouts** [comment] 2019-12-18 07:11
I don't have much time today, but you can check out https://github.com/fwouts/react-screenshot-test/compare/debug which will print out the URL of each component being tested. These URLs will only work while Jest is running though, so you gotta be quick to click on them!

**Comment by leicht-io** [comment] 2020-01-08 13:15
Hi again @fwouts and happy new year.

So I had some time to dig into this and I found of that this issue is caused by the CSS (and maybe the HTML) not being encoded correctly since we have CSS that matches DOM attributes e.g. 
```html
html[data-layout="dense"] {...}
``` 

The fix for me was to replace the characters which broke my DOM. This was done in line 120 in ReactComponentServer.ts:
```typescript
private renderWithoutStyledComponents(res: Response, node: NodeDescription) {
    // Simply render the node. This works with Emotion, too!
    const html = ReactDOMServer.renderToString(
      React.createElement(
        "html",
        null,
        React.createElement(
          "head",
          null,
          viewportMeta,
          ...node.remoteStylesheetUrls.map(url =>
            React.createElement("link", {
              rel: "stylesheet",
              href: url
            })
          ),
          React.createElement("style", null, readRecordedCss())
        ),
        React.createElement("body", null, node.reactNode)
      )
    );

    res.send(html.split("&quot;").join("\"").split("&#x27;").join("'"));
  }
```

This might not be the right solution but please let me know what you think.

**Comment by fwouts** [comment] 2020-01-09 03:29
OK, that makes sense! It turns out `React.createElement("style", null, readRecordedCss())` would escape the quotes.

A more focused fix is:
```js
            React.createElement("style", {
              dangerouslySetInnerHTML: { __html: readRecordedCss() }
            }),
```

Fix is in https://github.com/fwouts/react-screenshot-test/pull/76 :)

**Closed** 2020-01-09 03:38 UTC
